<?php

/* Do not edit this file. It shows an example for how to write 
   a template file. Copy this file to SOMETHING.php in the same
   directory as this file. Make changes to SOMETHING.php to 
   reflect the modifications you want. Then in Wordpress's
   Dashboard, go to SCABN configuration and select the 
   SOMETHING template.
   
   Note: You do not need to use the template system to modify
   SCABN -- it is designed to use wordpress hooks, so and 
   wordpress option (plugin, theme, etc) can modify it. So 
   instead of using SCABN's template, you could write your
   own plugin that executes code similar to what is shown below.
*/


function ShopingCartInfo($items) {
	//Use this function to return a message at the bottom of the checkout page.
	//Maybe a note about shipping options. Maybe a warning that you bought
	//a combination of items that doesn't make sense.
	return "";;
}





function getItemWeight($itemname,$qty,$inputweight) {
	//This is the function that sets the weight
	//for all items in your cart. If you want to use
	//the weight that is input by the user then just return
	//the $inputweight. This lets you set pricing in the simple
	//wordpress syntax of [scabn name="ItemName" weight="1.00"]

	//Note: Paypal doesn't like a weight of zero, this makes
	//sure weight it at least 0.01
	if ($inputweight <= 0.01) {
		$inputweight = 0.01;
	}
	return $inputweight;


	} 




function getShippingOptions($items) {
	//Currently only used for Google, as Paypal needs this hard-coded into
	//their website, this gives a list of the shipping options and pricing.
	//in principle this can be a function of them items being shipped
	//their weight, etc. 
	//We could put option on Paypal button for shipping, but shipping options
	//depend on shipping location which we don't ask for. So put your shipping
	//formula into paypal website. 
	//region can be "all" "NotUSA" or "USA"
	$ship=array();
	$ship[]=array("name" => "USPS Standard Shipping", "price" => "5", "region" => "all");
	$ship[]=array("name" => "USPS Priority Shipping (USA Only)", "price" => "10", "region" => "USA");
	$ship[]=array("name" => "USPS Express Shipping (USA Only)", "price" => "20", "region" => "USA");
	$ship[]=array("name" => "Global Priority (6-10 days)", "price" => "20", "region" => "NotUSA");
	$ship[]=array("name" => "Global Express (6 days)", "price" => "30", "region" => "NotUSA" );
	return $ship;
}


function displayCustomCartContents($items) {
	$output="";		
	if ($items) {			
		$output .="<table border='0' cellpadding='5' cellspacing='1' class='entryTable' align='center' width='96%'>	
		<thead>
		<tr class=\"thead\">
			<th scope=\"col\">Qty</th>
			<th scope=\"col\">Items</th>
			<th scope=\"col\" align=\"right\">Unit Price</th>
		</tr>
		</thead>";	
		$options = get_option('scabn_options');		
		$currency = apply_filters('scabn_display_currency_symbol',$options['currency']);						
		foreach($items as $item) {

			$output .= "<tr class = \"ck_content\">
				<td>" . $item['qty'] . "</td>            
				<td>" . $item['name'] ."</td>
				<td align='right'>" . $currency . number_format($item['price'],2) . "</td>
			</tr>";
			 
		}
		$output .= "</table>";		
	}
	return $output;
}


	
function display_paypal_receipt($keyarray) {
		//This is displayed on the checkout page url
		//When an order has been placed via paypal
		//and after the order is placed Paypal redirects
		//the shopper back here via PDT and auto return.
		//See Auto Return under paypal's Website
		//Payments section for more details.
		$output="";
		$firstname = $keyarray['first_name'];
		$lastname = $keyarray['last_name'];

		$amount = $keyarray['payment_gross'];

		$output .= "<p><h3>Checkout Complete -- Thank you for your purchase!</h3></p>";
		$output .= "<h4>Payment Details</h4><ul>\n";
		$output .= "<li>Name: $firstname $lastname</li>\n";
		$output .= "<li>Total Amount: $amount</li>\n";
		$output .= "</ul>";
		$output .= "You will receive a confirmation e-mail when payment for the order clears and a second email when your order ships. "; 
		$output .= "You may log into your paypal account at <a href=\"https://www.paypal.com/us\">paypal</a> to view details of this transaction.";
		return $output;
}



?>
